---
- name: Mini Project
  hosts: all
  become: yes
  tasks:
    - name: Installing HTTPD
      yum:
        name: httpd
        state: present

    - name: Starting HTTPD
      service:
        name: httpd
        state: started

    - name: Installing GIT
      yum:
        name: git
        state: present

    - name: Getting Code from GIT
      git:
        repo: https://github.com/Harsha6404/amazon-html.git
        dest: /var/www/html
