
- name: Setup Nginx and deploy website
  hosts: all
  become: yes

  tasks:
    - name: Enable nginx on Amazon Linux 2
      command: amazon-linux-extras enable nginx1

    - name: Install nginx
      yum:
        name: nginx
        state: absent

    - name: Start and enable nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Install git
      yum:
        name: git
        state: absent

    - name: Clone website from GitHub
      git:
        repo: https://github.com/Harsha6404/amazon-html.git
        dest: /usr/share/nginx/html

    - name: Restart nginx to apply changes
      service:
        name: nginx
        state: restarted

